### PR TITLE
Allow MemoryInfo block to be saved to disk

### PR DESCRIPTION
**Pull request by corytodd**
I am interested in this branch. It seems to work in my limited testing but let me know what else you had in mind for it and I'll implement it and get it to you for a possible merge.

### CODE REVIEW

**Review by GregTheDev — APPROVED** [review]

**Comment by GregTheDev** [comment]
Thanks for the pull request! I've had some pending changes on this branch locally to improve the usability and include a visual indicator showing which regions were available which were not (instead of showing an error message after you try and view/save the region). But real life got in the way of finishing them for now... I also have some other features that are mostly finished and just need a bit of tidying up and a proper release.

If you have any other feedback or suggestions please let me know :)

**Comment by corytodd** [comment]
Thanks for the quick response! I really like your use of memory mapped files in this project.

One feature I've been thinking about is a "save all memory from this module" context menu action. I know we can detect some of the block's based on their base address but I don't think that would capture everything. For example, when mspaint has an image in memory, the allocation will show in windbg via !heap but I'm not sure how to associate it back to the module. I can file a separate issue to discuss this further if you think this would be a useful feature.

**Comment by GregTheDev** [comment]
Sorry for the late reply, work has been crazy busy. You're right I don't think we'd be able to tie everything back to the module, at least not without an extra layer of interpretation. As you've seen crash dumps in their native state are very raw e.g. you can see what the allocation of memory regions looks like, but the memory region itself is just raw data. To make sense out of it you'd need to understand how the operating system used the memory. The heap is a perfect example, you'd have to find out where the heap is, before you then try to interpret it. But even then I'm not sure you'd be able to track an allocation back to the module, as it would depend on whether that kind of "ownership" information is even stored. It gets even more complication when you consider runtime like .net, java, python etc. They add their own abstractions on top of the operating system, so you'd need to understand those abstractions as well.

I think I remember that Handles however can be traced back to their owning module, I'll have to double check.

I am also typing this on Friday afternoon, so maybe I got it all wrong :)

**Comment by corytodd** [comment]
That's a really good point about various runtime heap abstractions, I appreciate your insight on the idea. If I think of anything other features that might be (actually) feasible I'll stop by again. 
Cheers!

**Pull request merged**
